- name: Install K3s master node
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    executable: /bin/bash
  become: yes

- name: Get k3s token
  ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  become: yes

- name: Set fact with k3s token
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token.stdout }}"
