- name: Install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Download GPG key using curl
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /tmp/docker.gpg
  args:
    creates: /tmp/docker.gpg

- name: Add key
  apt_key:
    file: /tmp/docker.gpg
    state: present

- name: Add repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker Engine
  apt:
    name: "{{ docker_package_name }}"
    state: latest
    update_cache: yes

- name: is up
  service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: yes
  notify: Restart docker
